### ISSUE TITLE
More nitpicky things

### ISSUE THREAD

**Issue by PeaWagon** [whitere123/CAS741_REW#18]
**Referencing**
- in section 2, you might want to write a sentence referencing the SRS tables since they contain most of your abbreviations and acronyms already
- first mention of PMBOK should have its own citation
- rogue wave is defined in SRS but modulated wave packet is not (if this is covered by intended reader characteristics, please ignore this comment)
- should capitalise MATLAB (section 6). 
- missing control section for the tests in the functional tests section

**Grammar Notes**
- in section 4.1 it should say "supervisor and me" not "supervisor and I", and the same in section 4.4 [https://en.oxforddictionaries.com/usage/i-or-me](url)
- in section 3.2, you mention "my supervisor", but you don't say who your supervisor is until the next section. Maybe just mention who he is in the introduction somewhere. You might not even need to mention that he is the supervisor (just state his name instead)
- i.e. not ie (section 7.3)
- for test-Rcon1 you should say "specific number" not "specific amount" since the points are a countable entity (I'm assuming) [https://grammarist.com/usage/amount-number/](url)

**Comment by whitere123** [comment]
Alright, thank you for this detailed issue. I made all of the necessary changes. I will close this soon.

**Comment by whitere123** [comment]
@smiths do we need your approval to close issues?

**Comment by smiths** [comment]
@whitere123, no you do not need my approval.  An issue would normally be close by the person it was assigned to when the issue was created.  @PeaWagon didn't actually assign you to this issue, but you should consider yourself assigned.  When closing an issue, you should say what you did to address the original problem.  Often this involves pointing to the commit the actually addresses the issue.

In some cases students close issues prematurely.  I'm most likely to notice on issues I've assigned to them.  When that occurs, I try to let the student know and reopen the issue.
